<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.1.0" />
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.4.1" />
    <PackageVersion Include="NetTopologySuite" Version="2.6.0" />
  </ItemGroup>
</Project>