<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>AsciiRaster.Parser</PackageId>
    <Version>1.1.2</Version>
    <Authors>Bjorn Kuiper</Authors>
    <Description>A .NET library for reading and parsing Esri ASCII raster (.asc) files, with optional conversion of AEDT Lambert Conformal Conic grids to WGS84.</Description>
    <PackageTags>esri;ascii;raster;asc;gis;parser</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/acrotron/Esri.AsciiRaster.Parser</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AsciiRaster.ParserTests" />
  </ItemGroup>

</Project>
